apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-config
  namespace: quiz-platform
data:
  APP_ENV: "production"
  HTTP_ADDR: ":8080"
  PG_HOST: "postgres"
  PG_PORT: "5433"
  PG_DATABASE: "quiz_prod"
  PG_SSL_MODE: "disable"
  REDIS_ADDR: "redis:6379"
  REDIS_DB: "0"
  REDIS_POOL_SIZE: "50"
  QUESTION_FETCH_TIMEOUT_SECONDS: "4s"
  DEFAULT_QUESTION_COUNT: "5"
  DEFAULT_PER_QUESTION_SECONDS: "15"
  GLOBAL_TIMEOUT_PADDING_SECONDS: "20"
  LEADERBOARD_SNAPSHOT_INTERVAL: "5m"
  LEADERBOARD_SNAPSHOT_TOP: "50"

