version: "3.9"

services:
  app:
    image: quiz-platform:latest
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - wrapper
    environment:
      APP_ENV: production
      AI_GENERATOR_URL: http://wrapper:9090
      AI_GENERATOR_API_KEY: ${AI_GENERATOR_API_KEY}

  wrapper:
    image: gemini-wrapper:latest
    env_file:
      - .env.prod
    environment:
      PORT: 9090
      GEMINI_MODEL: models/gemini-2.5-pro

  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - prod-db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  prod-db-data:
