version: "3.9"

services:
  app:
    build:
      context: ../../
    container_name: quiz-app-dev
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - wrapper
    environment:
      APP_ENV: development
      AI_GENERATOR_URL: http://wrapper:9090
      AI_GENERATOR_API_KEY: ${AI_GENERATOR_API_KEY}

  wrapper:
    build:
      context: ../../examples/ai/gemini-wrapper
      dockerfile: Dockerfile
    container_name: gemini-wrapper-dev
    env_file:
      - .env
    ports:
      - "9090:9090"
    environment:
      PORT: 9090
      GEMINI_MODEL: models/gemini-2.5-flash

  db:
    image: postgres:15
    env_file:
      - .env
    container_name: quiz-db-dev
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: quiz-redis-dev
    ports:
      - "6379:6379"

volumes:
  dev-db-data:


